/*
 ***********************************************************************
 *
 * 							  EdgeGraph3D
 *
 *         Copyright (C) 2018 Andrea Bignoli (andrea.bignoli@gmail.com)
 *                         All rights reserved
 *
 ***********************************************************************
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 *
*/


#ifndef INCLUDE_EDGEGRAPH3D_IO_INPUT_EDGE_GRAPH_3D_INPUT_PARAMS_HPP_
#define INCLUDE_EDGEGRAPH3D_IO_INPUT_EDGE_GRAPH_3D_INPUT_PARAMS_HPP_

#include "global_defines.hpp"
#include "global_switches.hpp"

typedef struct edge_matcher_input_params {
	char *images_folder;
	char *input_edges_folder;
	char *em_out_folder;
	char *input_plg_folder;
	char *real_camera_poses_file;
	bool real_camera_poses_file_valid;
	char *sfm_data_file;
	unsigned long original_refpoints;
	char *output_json;
	bool output_debug_images;
} edge_matcher_input_params;

/*
 * ++ Parameters ++
 *
 * - images_folder : folder containing input images
 * - input_edges_folder : folder containing input edge images w/ black background and white edges
 * - em_out_folder : working folder, will be used by the 3D edge reconstruction pipeline to output files
 * - sfm_data_file.json : input structure from motion data, in OpenMVG format
 * - output.json : output JSON file, in OpenMVG format, integrating the input file with edge-points sampled on edges generated by EdgeGraph3D
 *
 * ++ Optional parameters
 *
 * - [-i] : output debug images, i.e., 2D-to-2D polyline matching, edge-point reprojections
 * - [Disabled] real_camera_poses_file [-c] : file containing real camera poses
 *
 * ++ Call format
 *
 * 		edgeRec [-i] images/ edge_images/ working_folder/ input_sfm_data.json output.json
 *
 */
bool read_edge_matcher_input_params(int argc, char *argv[], edge_matcher_input_params &emip);

#endif /* INCLUDE_EDGEGRAPH3D_IO_INPUT_EDGE_GRAPH_3D_INPUT_PARAMS_HPP_ */
